### ISSUE TITLE
positive instruction disturbance?

### ISSUE THREAD

**Issue by xlchen0205** [p1k0pan/ICD#2]
您好，请问为什么Figure2中positive instruction disturbance也会加剧幻觉呢，在文中似乎没有看到您的解释。

根据以往的经验，positive instruction disturbance应该可以看作一种system prompt吧？这样的话理论上应该提高LVLM的性能，从而降低幻觉？

谢谢

**Comment by Ethanscuter** [comment]
您好，感谢对我们工作的关注。

关于指令干扰（正向和负向）的分析在文章的3.2节。在设计实验的时候我们希望正向指令能够增加模型的自信度（期待能减少幻象但是实验来看不是的），负向指令能够弱化模型的自信度。但是从实验结果来看，正向和负向指令都会增加多模态模型的幻象，一个可能原因是增加数据集中高频词或者和高频词共现的词从而增加了幻象。这也是文章的一个主要贡献。最后，使用ICD方法，使用正向和负向指令干扰都可以，因为负向指令幻象更大，根据我们的设计理念，能够剥离的幻象更多，因此使用负向指令更好。
